var continents = {"Afghanistan": "Asia","Albania":"Europe","Algeria":"Africa","American Samoa": "Oceania","Andorra": "Europe","Angola": "Africa","Anguilla": "North America","Antarctica": "Antarctica","Antigua and Barbuda": "North America","Argentina": "South America","Armenia": "Asia","Aruba": "North America","Australia": "Oceania","Austria": "Europe","Azerbaijan": "Asia","Bahamas": "North America","Bahrain": "Asia","Bangladesh": "Asia","Barbados": "North America","Belarus": "Europe","Belgium": "Europe","Belize": "North America","Benin": "Africa","Bermuda": "North America","Bhutan": "Asia","Bolivia": "South America","Bosnia and Herzegovina": "Europe","Botswana": "Africa","Bouvet Island": "Antarctica","Brazil": "South America","British Indian Ocean Territory": "Africa","Brunei": "Asia","Bulgaria": "Europe","Burkina Faso": "Africa","Burundi": "Africa","Cambodia": "Asia","Cameroon": "Africa","Canada": "North America","Cape Verde": "Africa","Cayman Islands": "North America","Central African Republic": "Africa","Chad": "Africa","Chile": "South America","China": "Asia","Christmas Island": "Oceania","Cocos (Keeling) Islands": "Oceania","Colombia": "South America","Comoros": "Africa","Congo": "Africa","Cook Islands": "Oceania","Costa Rica": "North America","Croatia": "Europe","Cuba": "North America","Cyprus": "Asia","Czech Republic": "Europe","Denmark": "Europe","Djibouti": "Africa","Dominica": "North America","Dominican Republic": "North America","East Timor": "Asia","Ecuador": "South America","Egypt": "Africa","El Salvador": "North America","England": "Europe","Equatorial Guinea": "Africa","Eritrea": "Africa","Estonia": "Europe","Ethiopia": "Africa","Falkland Islands": "South America","Faroe Islands": "Europe","Fiji Islands": "Oceania","Finland": "Europe","France": "Europe","French Guiana": "South America","French Polynesia": "Oceania","French Southern territories": "Antarctica","Gabon": "Africa","Gambia": "Africa","Georgia": "Asia","Germany": "Europe","Ghana": "Africa","Gibraltar": "Europe","Greece": "Europe","Greenland": "North America","Grenada": "North America","Guadeloupe": "North America","Guam": "Oceania","Guatemala": "North America","Guinea": "Africa","Guinea-Bissau": "Africa","Guyana": "South America","Haiti": "North America","Heard Island and McDonald Islands": "Antarctica","Holy See (Vatican City State)": "Europe","Honduras": "North America","Hong Kong": "Asia","Hungary": "Europe","Iceland": "Europe","India": "Asia","Indonesia": "Asia","Iran": "Asia","Iraq": "Asia","Ireland": "Europe","Israel": "Asia","Italy": "Europe","Ivory Coast": "Africa","Jamaica": "North America","Japan": "Asia","Jordan": "Asia","Kazakhstan": "Asia","Kenya": "Africa","Kiribati": "Oceania","Kuwait": "Asia","Kyrgyzstan": "Asia","Laos": "Asia","Latvia": "Europe","Lebanon": "Asia","Lesotho": "Africa","Liberia": "Africa","Libyan Arab Jamahiriya": "Africa","Liechtenstein": "Europe","Lithuania": "Europe","Luxembourg": "Europe","Macao": "Asia","North Macedonia": "Europe","Madagascar": "Africa","Malawi": "Africa","Malaysia": "Asia","Maldives": "Asia","Mali": "Africa","Malta": "Europe","Marshall Islands": "Oceania","Martinique": "North America","Mauritania": "Africa","Mauritius": "Africa","Mayotte": "Africa","Mexico": "North America","Micronesia, Federated States of": "Oceania","Moldova": "Europe","Monaco": "Europe","Mongolia": "Asia","Montenegro": "Europe","Montserrat": "North America","Morocco": "Africa","Mozambique": "Africa","Myanmar": "Asia","Namibia": "Africa","Nauru": "Oceania","Nepal": "Asia","Netherlands": "Europe","Netherlands Antilles": "North America","New Caledonia": "Oceania","New Zealand": "Oceania","Nicaragua": "North America","Niger": "Africa","Nigeria": "Africa","Niue": "Oceania","Norfolk Island": "Oceania","North Korea": "Asia","Northern Ireland": "Europe","Northern Mariana Islands": "Oceania","Norway": "Europe","Oman": "Asia","Pakistan": "Asia","Palau": "Oceania","Palestine": "Asia","Panama": "North America","Papua New Guinea": "Oceania","Paraguay": "South America","Peru": "South America","Philippines": "Asia","Pitcairn": "Oceania","Poland": "Europe","Portugal": "Europe","Puerto Rico": "North America","Qatar": "Asia","Reunion": "Africa","Romania": "Europe","Russia": "Europe","Rwanda": "Africa","Saint Helena": "Africa","Saint Kitts and Nevis": "North America","Saint Lucia": "North America","Saint Pierre and Miquelon": "North America","Saint Vincent and the Grenadines": "North America","Samoa": "Oceania","San Marino": "Europe","Sao Tome and Principe": "Africa","Saudi Arabia": "Asia","Scotland": "Europe","Senegal": "Africa","Seychelles": "Africa","Sierra Leone": "Africa","Singapore": "Asia","Slovakia": "Europe","Slovenia": "Europe","Solomon Islands": "Oceania","Somalia": "Africa","South Africa": "Africa","South Georgia and the South Sandwich Islands": "Antarctica","South Korea": "Asia","South Sudan": "Africa","Spain": "Europe","Sri Lanka": "Asia","Sudan": "Africa","Suriname": "South America","Svalbard and Jan Mayen": "Europe","Swaziland": "Africa","Sweden": "Europe","Switzerland": "Europe","Syria": "Asia","Tajikistan": "Asia","Tanzania": "Africa","Thailand": "Asia","The Democratic Republic of Congo": "Africa","Togo": "Africa","Tokelau": "Oceania","Tonga": "Oceania","Trinidad and Tobago": "North America","Tunisia": "Africa","Turkey": "Asia","Turkmenistan": "Asia","Turks and Caicos Islands": "North America","Tuvalu": "Oceania","Uganda": "Africa","Ukraine": "Europe","United Arab Emirates": "Asia","United Kingdom": "Europe","United States": "North America","United States Minor Outlying Islands": "Oceania","Uruguay": "South America","Uzbekistan": "Asia","Vanuatu": "Oceania","Venezuela": "South America","Vietnam": "Asia","Virgin Islands, British": "North America","Virgin Islands, U.S.": "North America","Wales": "Europe","Wallis and Futuna": "Oceania","Western Sahara": "Africa","Yemen": "Asia","Yugoslavia": "Europe","Zambia": "Africa","Zimbabwe": "Africa"}

var capitals = {"Afghanistan":"Kabul","Albania":"Tirana","Algeria":"Alger","American Samoa":"Fagatogo","Andorra":"Andorra la Vella","Angola":"Luanda","Anguilla":"The Valley","Antarctica":null,"Antigua and Barbuda":"Saint John's","Argentina":"Buenos Aires","Armenia":"Yerevan","Aruba":"Oranjestad","Australia":"Canberra","Austria":"Wien","Azerbaijan":"Baku","Bahamas":"Nassau","Bahrain":"al-Manama","Bangladesh":"Dhaka","Barbados":"Bridgetown","Belarus":"Minsk","Belgium":"Bruxelles [Brussel]","Belize":"Belmopan","Benin":"Porto-Novo","Bermuda":"Hamilton","Bhutan":"Thimphu","Bolivia":"La Paz","Bosnia and Herzegovina":"Sarajevo","Botswana":"Gaborone","Bouvet Island":null,"Brazil":"Brasília","British Indian Ocean Territory":null,"Brunei":"Bandar Seri Begawan","Bulgaria":"Sofia","Burkina Faso":"Ouagadougou","Burundi":"Bujumbura","Cambodia":"Phnom Penh","Cameroon":"Yaound","Canada":"Ottawa","Cape Verde":"Praia","Cayman Islands":"George Town","Central African Republic":"Bangui","Chad":"N'Djam","Chile":"Santiago de Chile","China":"Peking","Christmas Island":"Flying Fish Cove","Cocos (Keeling) Islands":"West Island","Colombia":"Santaf","Comoros":"Moroni","Congo":"Brazzaville","Cook Islands":"Avarua","Costa Rica":"San Jos","Croatia":"Zagreb","Cuba":"La Habana","Cyprus":"Nicosia","Czech Republic":"Praha","Denmark":"Copenhagen","Djibouti":"Djibouti","Dominica":"Roseau","Dominican Republic":"Santo Domingo de Guzm","East Timor":"Dili","Ecuador":"Quito","Egypt":"Cairo","El Salvador":"San Salvador","England":"London","Equatorial Guinea":"Malabo","Eritrea":"Asmara","Estonia":"Tallinn","Ethiopia":"Addis Abeba","Falkland Islands":"Stanley","Faroe Islands":"Tórshavn","Fiji Islands":"Suva","Finland":"Helsinki [Helsingfors]","France":"Paris","French Guiana":"Cayenne","French Polynesia":"Papeete","French Southern territories":null,"Gabon":"Libreville","Gambia":"Banjul","Georgia":"Tbilisi","Germany":"Berlin","Ghana":"Accra","Gibraltar":"Gibraltar","Greece":"Athenai","Greenland":"Nuuk","Grenada":"Saint George's","Guadeloupe":"Basse-Terre","Guam":"Aga","Guatemala":"Ciudad de Guatemala","Guinea":"Conakry","Guinea-Bissau":"Bissau","Guyana":"Georgetown","Haiti":"Port-au-Prince","Heard Island and McDonald Islands":null,"Holy See (Vatican City State)":"Citt","Honduras":"Tegucigalpa","Hong Kong":"Victoria","Hungary":"Budapest","Iceland":"Reykjav","India":"New Delhi","Indonesia":"Jakarta","Iran":"Tehran","Iraq":"Baghdad","Ireland":"Dublin","Israel":"Jerusalem","Italy":"Roma","Ivory Coast":"Yamoussoukro","Jamaica":"Kingston","Japan":"Tokyo","Jordan":"Amman","Kazakhstan":"Astana","Kenya":"Nairobi","Kiribati":"Bairiki","Kuwait":"Kuwait","Kyrgyzstan":"Bishkek","Laos":"Vientiane","Latvia":"Riga","Lebanon":"Beirut","Lesotho":"Maseru","Liberia":"Monrovia","Libyan Arab Jamahiriya":"Tripoli","Liechtenstein":"Vaduz","Lithuania":"Vilnius","Luxembourg":"Luxembourg [Luxemburg/L","Macao":"Macao","North Macedonia":"Skopje","Madagascar":"Antananarivo","Malawi":"Lilongwe","Malaysia":"Kuala Lumpur","Maldives":"Male","Mali":"Bamako","Malta":"Valletta","Marshall Islands":"Dalap-Uliga-Darrit","Martinique":"Fort-de-France","Mauritania":"Nouakchott","Mauritius":"Port-Louis","Mayotte":"Mamoutzou","Mexico":"Ciudad de M","Micronesia, Federated States of":"Palikir","Moldova":"Chisinau","Monaco":"Monaco-Ville","Mongolia":"Ulan Bator","Montenegro":"Podgorica","Montserrat":"Plymouth","Morocco":"Rabat","Mozambique":"Maputo","Myanmar":"Rangoon (Yangon)","Namibia":"Windhoek","Nauru":"Yaren","Nepal":"Kathmandu","Netherlands":"Amsterdam","Netherlands Antilles":"Willemstad","New Caledonia":"Noum","New Zealand":"Wellington","Nicaragua":"Managua","Niger":"Niamey","Nigeria":"Abuja","Niue":"Alofi","Norfolk Island":"Kingston","North Korea":"Pyongyang","Northern Ireland":"Belfast","Northern Mariana Islands":"Garapan","Norway":"Oslo","Oman":"Masqat","Pakistan":"Islamabad","Palau":"Koror","Palestine":"Gaza","Panama":"Ciudad de Panam","Papua New Guinea":"Port Moresby","Paraguay":"Asunci","Peru":"Lima","Philippines":"Manila","Pitcairn":"Adamstown","Poland":"Warszawa","Portugal":"Lisboa","Puerto Rico":"San Juan","Qatar":"Doha","Reunion":"Saint-Denis","Romania":"Bucuresti","Russian Federation":"Moscow","Rwanda":"Kigali","Saint Helena":"Jamestown","Saint Kitts and Nevis":"Basseterre","Saint Lucia":"Castries","Saint Pierre and Miquelon":"Saint-Pierre","Saint Vincent and the Grenadines":"Kingstown","Samoa":"Apia","San Marino":"San Marino","Sao Tome and Principe":"S","Saudi Arabia":"Riyadh","Scotland":"Edinburgh","Senegal":"Dakar","Seychelles":"Victoria","Sierra Leone":"Freetown","Singapore":"Singapore","Slovakia":"Bratislava","Slovenia":"Ljubljana","Solomon Islands":"Honiara","Somalia":"Mogadishu","South Africa":"Pretoria","South Georgia and the South Sandwich Islands":null,"South Korea":"Seoul","South Sudan":"Juba","Spain":"Madrid","SriLanka":null,"Sudan":"Khartum","Suriname":"Paramaribo","Svalbard and Jan Mayen":"Longyearbyen","Swaziland":"Mbabane","Sweden":"Stockholm","Switzerland":"Bern","Syria":"Damascus","Tajikistan":"Dushanbe","Tanzania":"Dodoma","Thailand":"Bangkok","The Democratic Republic of Congo":"Kinshasa","Togo":"Lom","Tokelau":"Fakaofo","Tonga":"Nuku'alofa","Trinidad and Tobago":"Port-of-Spain","Tunisia":"Tunis","Turkey":"Ankara","Turkmenistan":"Ashgabat","Turks and Caicos Islands":"Cockburn Town","Tuvalu":"Funafuti","Uganda":"Kampala","Ukraine":"Kyiv","United Arab Emirates":"Abu Dhabi","United Kingdom":"London","United States":"Washington","United States Minor Outlying Islands":null,"Uruguay":"Montevideo","Uzbekistan":"Toskent","Vanuatu":"Port-Vila","Venezuela":"Caracas","Vietnam":"Hanoi","Virgin Islands, British":"Road Town","Virgin Islands, U.S.":"Charlotte Amalie","Wales":"Cardiff","Wallis and Futuna":"Mata-Utu","Western Sahara":"El-Aai","Yemen":"Sanaa","Yugoslavia":"Beograd","Zambia":"Lusaka","Zimbabwe":"Harare"}


var countryINFO = {
"AF":{"name":"Afghanistan","continent":continents["Afghanistan"],"capital":capitals["Afghanistan"]},
"AL":{"name":"Albania","continent":continents["Albania"],"capital":capitals["Albania"]},
"DZ":{"name":"Algeria","continent":continents["Algeria"],"capital":capitals["Algeria"]},
"AS":{"name":"American Samoa","continent":continents["American Samoa"],"capital":capitals["American Samoa"]},
"AD":{"name":"Andorra","continent":continents["Andorra"],"capital":capitals["Andorra"]},
"AO":{"name":"Angola","continent":continents["Angola"],"capital":capitals["Angola"]},
"AI":{"name":"Anguilla","continent":continents["Anguilla"],"capital":capitals["Anguilla"]},
"AQ":{"name":"Antarctica","continent":continents["Antarctica"],"capital":capitals["Antarctica"]},
"AG":{"name":"Antigua and Barbuda","continent":continents["Antigua and Barbuda"],"capital":capitals["Antigua and Barbuda"]},
"AR":{"name":"Argentina","continent":continents["Argentina"],"capital":capitals["Argentina"]},
"AM":{"name":"Armenia","continent":continents["Armenia"],"capital":capitals["Armenia"]},
"AW":{"name":"Aruba","continent":continents["Aruba"],"capital":capitals["Aruba"]},
"AU":{"name":"Australia","continent":continents["Australia"],"capital":capitals["Australia"]},
"AT":{"name":"Austria","continent":continents["Austria"],"capital":capitals["Austria"]},
"AZ":{"name":"Azerbaijan","continent":continents["Azerbaijan"],"capital":capitals["Azerbaijan"]},
"BS":{"name":"Bahamas","continent":continents["Bahamas"],"capital":capitals["Bahamas"]},
"BH":{"name":"Bahrain","continent":continents["Bahrain"],"capital":capitals["Bahrain"]},
"BD":{"name":"Bangladesh","continent":continents["Bangladesh"],"capital":capitals["Bangladesh"]},
"BB":{"name":"Barbados","continent":continents["Barbados"],"capital":capitals["Barbados"]},
"BY":{"name":"Belarus","continent":continents["Belarus"],"capital":capitals["Belarus"]},
"BE":{"name":"Belgium","continent":continents["Belgium"],"capital":capitals["Belgium"]},
"BZ":{"name":"Belize","continent":continents["Belize"],"capital":capitals["Belize"]},
"BJ":{"name":"Benin","continent":continents["Benin"],"capital":capitals["Benin"]},
"BM":{"name":"Bermuda","continent":continents["Bermuda"],"capital":capitals["Bermuda"]},
"BT":{"name":"Bhutan","continent":continents["Bhutan"],"capital":capitals["Bhutan"]},
"BO":{"name":"Bolivia","continent":continents["Bolivia"],"capital":capitals["Bolivia"]},
"BA":{"name":"Bosnia and Herzegovina","continent":continents["Bosnia and Herzegovina"],"capital":capitals["Bosnia and Herzegovina"]},
"BW":{"name":"Botswana","continent":continents["Botswana"],"capital":capitals["Botswana"]},
"BV":{"name":"Bouvet Island","continent":continents["Bouvet Island"],"capital":capitals["Bouvet Island"]},
"BR":{"name":"Brazil","continent":continents["Brazil"],"capital":capitals["Brazil"]},
"IO":{"name":"British Indian Ocean Territory","continent":continents["British Indian Ocean Territory"],"capital":capitals["British Indian Ocean Territory"]},
"BN":{"name":"Brunei","continent":continents["Brunei"],"capital":capitals["Brunei"]},
"BG":{"name":"Bulgaria","continent":continents["Bulgaria"],"capital":capitals["Bulgaria"]},
"BF":{"name":"Burkina Faso","continent":continents["Burkina Faso"],"capital":capitals["Burkina Faso"]},
"BI":{"name":"Burundi","continent":continents["Burundi"],"capital":capitals["Burundi"]},
"KH":{"name":"Cambodia","continent":continents["Cambodia"],"capital":capitals["Cambodia"]},
"CM":{"name":"Cameroon","continent":continents["Cameroon"],"capital":capitals["Cameroon"]},
"CA":{"name":"Canada","continent":continents["Canada"],"capital":capitals["Canada"]},
"CV":{"name":"Cape Verde","continent":continents["Cape Verde"],"capital":capitals["Cape Verde"]},
"KY":{"name":"Cayman Islands","continent":continents["Cayman Islands"],"capital":capitals["Cayman Islands"]},
"CF":{"name":"Central African Republic","continent":continents["Central African Republic"],"capital":capitals["Central African Republic"]},
"TD":{"name":"Chad","continent":continents["Chad"],"capital":capitals["Chad"]},
"CL":{"name":"Chile","continent":continents["Chile"],"capital":capitals["Chile"]},
"CN":{"name":"China","continent":continents["China"],"capital":capitals["China"]},
"CX":{"name":"Christmas Island","continent":continents["Christmas Island"],"capital":capitals["Christmas Island"]},
"CC":{"name":"Cocos (Keeling) Islands","continent":continents["Cocos (Keeling) Islands"],"capital":capitals["Cocos (Keeling) Islands"]},
"CO":{"name":"Colombia","continent":continents["Colombia"],"capital":capitals["Colombia"]},
"KM":{"name":"Comoros","continent":continents["Comoros"],"capital":capitals["Comoros"]},
"CG":{"name":"Congo","continent":continents["Congo"],"capital":capitals["Congo"]},
"CK":{"name":"Cook Islands","continent":continents["Cook Islands"],"capital":capitals["Cook Islands"]},
"CR":{"name":"Costa Rica","continent":continents["Costa Rica"],"capital":capitals["Costa Rica"]},
"HR":{"name":"Croatia","continent":continents["Croatia"],"capital":capitals["Croatia"]},
"CU":{"name":"Cuba","continent":continents["Cuba"],"capital":capitals["Cuba"]},
"CY":{"name":"Cyprus","continent":continents["Cyprus"],"capital":capitals["Cyprus"]},
"CZ":{"name":"Czech Republic","continent":continents["Czech Republic"],"capital":capitals["Czech Republic"]},
"DK":{"name":"Denmark","continent":continents["Denmark"],"capital":capitals["Denmark"]},
"DJ":{"name":"Djibouti","continent":continents["Djibouti"],"capital":capitals["Djibouti"]},
"DM":{"name":"Dominica","continent":continents["Dominica"],"capital":capitals["Dominica"]},
"DO":{"name":"Dominican Republic","continent":continents["Dominican Republic"],"capital":capitals["Dominican Republic"]},
"TP":{"name":"East Timor","continent":continents["East Timor"],"capital":capitals["East Timor"]},
"EC":{"name":"Ecuador","continent":continents["Ecuador"],"capital":capitals["Ecuador"]},
"EG":{"name":"Egypt","continent":continents["Egypt"],"capital":capitals["Egypt"]},
"SV":{"name":"El Salvador","continent":continents["El Salvador"],"capital":capitals["El Salvador"]},
"GQ":{"name":"Equatorial Guinea","continent":continents["Equatorial Guinea"],"capital":capitals["Equatorial Guinea"]},
"ER":{"name":"Eritrea","continent":continents["Eritrea"],"capital":capitals["Eritrea"]},
"EE":{"name":"Estonia","continent":continents["Estonia"],"capital":capitals["Estonia"]},
"ET":{"name":"Ethiopia","continent":continents["Ethiopia"],"capital":capitals["Ethiopia"]},
"FK":{"name":"Falkland Islands","continent":continents["Falkland Islands"],"capital":capitals["Falkland Islands"]},
"FO":{"name":"Faroe Islands","continent":continents["Faroe Islands"],"capital":capitals["Faroe Islands"]},
"FJ":{"name":"Fiji Islands","continent":continents["Fiji Islands"],"capital":capitals["Fiji Islands"]},
"FI":{"name":"Finland","continent":continents["Finland"],"capital":capitals["Finland"]},
"FR":{"name":"France","continent":continents["France"],"capital":capitals["France"]},
"GF":{"name":"French Guiana","continent":continents["French Guiana"],"capital":capitals["French Guiana"]},
"PF":{"name":"French Polynesia","continent":continents["French Polynesia"],"capital":capitals["French Polynesia"]},
"TF":{"name":"French Southern territories","continent":continents["French Southern territories"],"capital":capitals["French Southern territories"]},
"GA":{"name":"Gabon","continent":continents["Gabon"],"capital":capitals["Gabon"]},
"GM":{"name":"Gambia","continent":continents["Gambia"],"capital":capitals["Gambia"]},
"GE":{"name":"Georgia","continent":continents["Georgia"],"capital":capitals["Georgia"]},
"DE":{"name":"Germany","continent":continents["Germany"],"capital":capitals["Germany"]},
"GH":{"name":"Ghana","continent":continents["Ghana"],"capital":capitals["Ghana"]},
"GI":{"name":"Gibraltar","continent":continents["Gibraltar"],"capital":capitals["Gibraltar"]},
"GR":{"name":"Greece","continent":continents["Greece"],"capital":capitals["Greece"]},
"GL":{"name":"Greenland","continent":continents["Greenland"],"capital":capitals["Greenland"]},
"GD":{"name":"Grenada","continent":continents["Grenada"],"capital":capitals["Grenada"]},
"GP":{"name":"Guadeloupe","continent":continents["Guadeloupe"],"capital":capitals["Guadeloupe"]},
"GU":{"name":"Guam","continent":continents["Guam"],"capital":capitals["Guam"]},
"GT":{"name":"Guatemala","continent":continents["Guatemala"],"capital":capitals["Guatemala"]},
"GG":{"name":"Guernsey","continent":continents["Guernsey"],"capital":capitals["Guernsey"]},
"GN":{"name":"Guinea","continent":continents["Guinea"],"capital":capitals["Guinea"]},
"GW":{"name":"Guinea-Bissau","continent":continents["Guinea-Bissau"],"capital":capitals["Guinea-Bissau"]},
"GY":{"name":"Guyana","continent":continents["Guyana"],"capital":capitals["Guyana"]},
"HT":{"name":"Haiti","continent":continents["Haiti"],"capital":capitals["Haiti"]},
"HM":{"name":"Heard Island and McDonald Islands","continent":continents["Heard Island and McDonald Islands"],"capital":capitals["Heard Island and McDonald Islands"]},
"VA":{"name":"Holy See (Vatican City State)","continent":continents["Holy See (Vatican City State)"],"capital":capitals["Holy See (Vatican City State)"]},
"HN":{"name":"Honduras","continent":continents["Honduras"],"capital":capitals["Honduras"]},
"HK":{"name":"Hong Kong","continent":continents["Hong Kong"],"capital":capitals["Hong Kong"]},
"HU":{"name":"Hungary","continent":continents["Hungary"],"capital":capitals["Hungary"]},
"IS":{"name":"Iceland","continent":continents["Iceland"],"capital":capitals["Iceland"]},
"IN":{"name":"India","continent":continents["India"],"capital":capitals["India"]},
"ID":{"name":"Indonesia","continent":continents["Indonesia"],"capital":capitals["Indonesia"]},
"IR":{"name":"Iran","continent":continents["Iran"],"capital":capitals["Iran"]},
"IQ":{"name":"Iraq","continent":continents["Iraq"],"capital":capitals["Iraq"]},
"IE":{"name":"Ireland","continent":continents["Ireland"],"capital":capitals["Ireland"]},
"IM":{"name":"Isle of Man","continent":continents["Isle of Man"],"capital":capitals["Isle of Man"]},
"IL":{"name":"Israel","continent":continents["Israel"],"capital":capitals["Israel"]},
"IT":{"name":"Italy","continent":continents["Italy"],"capital":capitals["Italy"]},
"CI":{"name":"Ivory Coast","continent":continents["Ivory Coast"],"capital":capitals["Ivory Coast"]},
"JM":{"name":"Jamaica","continent":continents["Jamaica"],"capital":capitals["Jamaica"]},
"JP":{"name":"Japan","continent":continents["Japan"],"capital":capitals["Japan"]},
"JE":{"name":"Jersey","continent":continents["Jersey"],"capital":capitals["Jersey"]},
"JO":{"name":"Jordan","continent":continents["Jordan"],"capital":capitals["Jordan"]},
"KZ":{"name":"Kazakhstan","continent":continents["Kazakhstan"],"capital":capitals["Kazakhstan"]},
"KE":{"name":"Kenya","continent":continents["Kenya"],"capital":capitals["Kenya"]},
"KI":{"name":"Kiribati","continent":continents["Kiribati"],"capital":capitals["Kiribati"]},
"KW":{"name":"Kuwait","continent":continents["Kuwait"],"capital":capitals["Kuwait"]},
"KG":{"name":"Kyrgyzstan","continent":continents["Kyrgyzstan"],"capital":capitals["Kyrgyzstan"]},
"LA":{"name":"Laos","continent":continents["Laos"],"capital":capitals["Laos"]},
"LV":{"name":"Latvia","continent":continents["Latvia"],"capital":capitals["Latvia"]},
"LB":{"name":"Lebanon","continent":continents["Lebanon"],"capital":capitals["Lebanon"]},
"LS":{"name":"Lesotho","continent":continents["Lesotho"],"capital":capitals["Lesotho"]},
"LR":{"name":"Liberia","continent":continents["Liberia"],"capital":capitals["Liberia"]},
"LY":{"name":"Libyan Arab Jamahiriya","continent":continents["Libyan Arab Jamahiriya"],"capital":capitals["Libyan Arab Jamahiriya"]},
"LI":{"name":"Liechtenstein","continent":continents["Liechtenstein"],"capital":capitals["Liechtenstein"]},
"LT":{"name":"Lithuania","continent":continents["Lithuania"],"capital":capitals["Lithuania"]},
"LU":{"name":"Luxembourg","continent":continents["Luxembourg"],"capital":capitals["Luxembourg"]},
"MO":{"name":"Macao","continent":continents["Macao"],"capital":capitals["Macao"]},
"MK":{"name":"North Macedonia","continent":continents["North Macedonia"],"capital":capitals["North Macedonia"]},
"MG":{"name":"Madagascar","continent":continents["Madagascar"],"capital":capitals["Madagascar"]},
"MW":{"name":"Malawi","continent":continents["Malawi"],"capital":capitals["Malawi"]},
"MY":{"name":"Malaysia","continent":continents["Malaysia"],"capital":capitals["Malaysia"]},
"MV":{"name":"Maldives","continent":continents["Maldives"],"capital":capitals["Maldives"]},
"ML":{"name":"Mali","continent":continents["Mali"],"capital":capitals["Mali"]},
"MT":{"name":"Malta","continent":continents["Malta"],"capital":capitals["Malta"]},
"MH":{"name":"Marshall Islands","continent":continents["Marshall Islands"],"capital":capitals["Marshall Islands"]},
"MQ":{"name":"Martinique","continent":continents["Martinique"],"capital":capitals["Martinique"]},
"MR":{"name":"Mauritania","continent":continents["Mauritania"],"capital":capitals["Mauritania"]},
"MU":{"name":"Mauritius","continent":continents["Mauritius"],"capital":capitals["Mauritius"]},
"YT":{"name":"Mayotte","continent":continents["Mayotte"],"capital":capitals["Mayotte"]},
"MX":{"name":"Mexico","continent":continents["Mexico"],"capital":capitals["Mexico"]},
"FM":{"name":"Micronesia, Federated States of","continent":continents["Micronesia, Federated States of"],"capital":capitals["Micronesia, Federated States of"]},
"MD":{"name":"Moldova","continent":continents["Moldova"],"capital":capitals["Moldova"]},
"MC":{"name":"Monaco","continent":continents["Monaco"],"capital":capitals["Monaco"]},
"MN":{"name":"Mongolia","continent":continents["Mongolia"],"capital":capitals["Mongolia"]},
"ME":{"name":"Montenegro","continent":continents["Montenegro"],"capital":capitals["Montenegro"]},
"MS":{"name":"Montserrat","continent":continents["Montserrat"],"capital":capitals["Montserrat"]},
"MA":{"name":"Morocco","continent":continents["Morocco"],"capital":capitals["Morocco"]},
"MZ":{"name":"Mozambique","continent":continents["Mozambique"],"capital":capitals["Mozambique"]},
"MM":{"name":"Myanmar","continent":continents["Myanmar"],"capital":capitals["Myanmar"]},
"NA":{"name":"Namibia","continent":continents["Namibia"],"capital":capitals["Namibia"]},
"NR":{"name":"Nauru","continent":continents["Nauru"],"capital":capitals["Nauru"]},
"NP":{"name":"Nepal","continent":continents["Nepal"],"capital":capitals["Nepal"]},
"NL":{"name":"Netherlands","continent":continents["Netherlands"],"capital":capitals["Netherlands"]},
"AN":{"name":"Netherlands Antilles","continent":continents["Netherlands Antilles"],"capital":capitals["Netherlands Antilles"]},
"NC":{"name":"New Caledonia","continent":continents["New Caledonia"],"capital":capitals["New Caledonia"]},
"NZ":{"name":"New Zealand","continent":continents["New Zealand"],"capital":capitals["New Zealand"]},
"NI":{"name":"Nicaragua","continent":continents["Nicaragua"],"capital":capitals["Nicaragua"]},
"NE":{"name":"Niger","continent":continents["Niger"],"capital":capitals["Niger"]},
"NG":{"name":"Nigeria","continent":continents["Nigeria"],"capital":capitals["Nigeria"]},
"NU":{"name":"Niue","continent":continents["Niue"],"capital":capitals["Niue"]},
"NF":{"name":"Norfolk Island","continent":continents["Norfolk Island"],"capital":capitals["Norfolk Island"]},
"KP":{"name":"North Korea","continent":continents["North Korea"],"capital":capitals["North Korea"]},
"GB":{"name":"Northern Ireland","continent":continents["Northern Ireland"],"capital":capitals["Northern Ireland"]},
"MP":{"name":"Northern Mariana Islands","continent":continents["Northern Mariana Islands"],"capital":capitals["Northern Mariana Islands"]},
"NO":{"name":"Norway","continent":continents["Norway"],"capital":capitals["Norway"]},
"OM":{"name":"Oman","continent":continents["Oman"],"capital":capitals["Oman"]},
"PK":{"name":"Pakistan","continent":continents["Pakistan"],"capital":capitals["Pakistan"]},
"PW":{"name":"Palau","continent":continents["Palau"],"capital":capitals["Palau"]},
"PS":{"name":"Palestine","continent":continents["Palestine"],"capital":capitals["Palestine"]},
"PA":{"name":"Panama","continent":continents["Panama"],"capital":capitals["Panama"]},
"PG":{"name":"Papua New Guinea","continent":continents["Papua New Guinea"],"capital":capitals["Papua New Guinea"]},
"PY":{"name":"Paraguay","continent":continents["Paraguay"],"capital":capitals["Paraguay"]},
"PE":{"name":"Peru","continent":continents["Peru"],"capital":capitals["Peru"]},
"PH":{"name":"Philippines","continent":continents["Philippines"],"capital":capitals["Philippines"]},
"PN":{"name":"Pitcairn","continent":continents["Pitcairn"],"capital":capitals["Pitcairn"]},
"PL":{"name":"Poland","continent":continents["Poland"],"capital":capitals["Poland"]},
"PT":{"name":"Portugal","continent":continents["Portugal"],"capital":capitals["Portugal"]},
"PR":{"name":"Puerto Rico","continent":continents["Puerto Rico"],"capital":capitals["Puerto Rico"]},
"QA":{"name":"Qatar","continent":continents["Qatar"],"capital":capitals["Qatar"]},
"RE":{"name":"Reunion","continent":continents["Reunion"],"capital":capitals["Reunion"]},
"RO":{"name":"Romania","continent":continents["Romania"],"capital":capitals["Romania"]},
"RU":{"name":"Russian Federation","continent":continents["Russian Federation"],"capital":capitals["Russian Federation"]},
"RW":{"name":"Rwanda","continent":continents["Rwanda"],"capital":capitals["Rwanda"]},
"SH":{"name":"Saint Helena","continent":continents["Saint Helena"],"capital":capitals["Saint Helena"]},
"KN":{"name":"Saint Kitts and Nevis","continent":continents["Saint Kitts and Nevis"],"capital":capitals["Saint Kitts and Nevis"]},
"LC":{"name":"Saint Lucia","continent":continents["Saint Lucia"],"capital":capitals["Saint Lucia"]},
"PM":{"name":"Saint Pierre and Miquelon","continent":continents["Saint Pierre and Miquelon"],"capital":capitals["Saint Pierre and Miquelon"]},
"VC":{"name":"Saint Vincent and the Grenadines","continent":continents["Saint Vincent and the Grenadines"],"capital":capitals["Saint Vincent and the Grenadines"]},
"WS":{"name":"Samoa","continent":continents["Samoa"],"capital":capitals["Samoa"]},
"SM":{"name":"San Marino","continent":continents["San Marino"],"capital":capitals["San Marino"]},
"ST":{"name":"Sao Tome and Principe","continent":continents["Sao Tome and Principe"],"capital":capitals["Sao Tome and Principe"]},
"SA":{"name":"Saudi Arabia","continent":continents["Saudi Arabia"],"capital":capitals["Saudi Arabia"]},
"SN":{"name":"Senegal","continent":continents["Senegal"],"capital":capitals["Senegal"]},
"RS":{"name":"Serbia","continent":continents["Serbia"],"capital":capitals["Serbia"]},
"SC":{"name":"Seychelles","continent":continents["Seychelles"],"capital":capitals["Seychelles"]},
"SL":{"name":"Sierra Leone","continent":continents["Sierra Leone"],"capital":capitals["Sierra Leone"]},
"SG":{"name":"Singapore","continent":continents["Singapore"],"capital":capitals["Singapore"]},
"SK":{"name":"Slovakia","continent":continents["Slovakia"],"capital":capitals["Slovakia"]},
"SI":{"name":"Slovenia","continent":continents["Slovenia"],"capital":capitals["Slovenia"]},
"SB":{"name":"Solomon Islands","continent":continents["Solomon Islands"],"capital":capitals["Solomon Islands"]},
"SO":{"name":"Somalia","continent":continents["Somalia"],"capital":capitals["Somalia"]},
"ZA":{"name":"South Africa","continent":continents["South Africa"],"capital":capitals["South Africa"]},
"GS":{"name":"South Georgia and the South Sandwich Islands","continent":continents["South Georgia and the South Sandwich Islands"],"capital":capitals["South Georgia and the South Sandwich Islands"]},
"KR":{"name":"South Korea","continent":continents["South Korea"],"capital":capitals["South Korea"]},
"SS":{"name":"South Sudan","continent":continents["South Sudan"],"capital":capitals["South Sudan"]},
"ES":{"name":"Spain","continent":continents["Spain"],"capital":capitals["Spain"]},
"LK":{"name":"Sri Lanka","continent":continents["Sri Lanka"],"capital":capitals["Sri Lanka"]},
"SD":{"name":"Sudan","continent":continents["Sudan"],"capital":capitals["Sudan"]},
"SR":{"name":"Suriname","continent":continents["Suriname"],"capital":capitals["Suriname"]},
"SJ":{"name":"Svalbard and Jan Mayen","continent":continents["Svalbard and Jan Mayen"],"capital":capitals["Svalbard and Jan Mayen"]},
"SZ":{"name":"Swaziland","continent":continents["Swaziland"],"capital":capitals["Swaziland"]},
"SE":{"name":"Sweden","continent":continents["Sweden"],"capital":capitals["Sweden"]},
"CH":{"name":"Switzerland","continent":continents["Switzerland"],"capital":capitals["Switzerland"]},
"SY":{"name":"Syria","continent":continents["Syria"],"capital":capitals["Syria"]},
"TJ":{"name":"Tajikistan","continent":continents["Tajikistan"],"capital":capitals["Tajikistan"]},
"TZ":{"name":"Tanzania","continent":continents["Tanzania"],"capital":capitals["Tanzania"]},
"TH":{"name":"Thailand","continent":continents["Thailand"],"capital":capitals["Thailand"]},
"CD":{"name":"The Democratic Republic of Congo","continent":continents["The Democratic Republic of Congo"],"capital":capitals["The Democratic Republic of Congo"]},
"TL":{"name":"Timor-Leste","continent":continents["Timor-Leste"],"capital":capitals["Timor-Leste"]},
"TG":{"name":"Togo","continent":continents["Togo"],"capital":capitals["Togo"]},
"TK":{"name":"Tokelau","continent":continents["Tokelau"],"capital":capitals["Tokelau"]},
"TO":{"name":"Tonga","continent":continents["Tonga"],"capital":capitals["Tonga"]},
"TT":{"name":"Trinidad and Tobago","continent":continents["Trinidad and Tobago"],"capital":capitals["Trinidad and Tobago"]},
"TN":{"name":"Tunisia","continent":continents["Tunisia"],"capital":capitals["Tunisia"]},
"TR":{"name":"Turkey","continent":continents["Turkey"],"capital":capitals["Turkey"]},
"TM":{"name":"Turkmenistan","continent":continents["Turkmenistan"],"capital":capitals["Turkmenistan"]},
"TC":{"name":"Turks and Caicos Islands","continent":continents["Turks and Caicos Islands"],"capital":capitals["Turks and Caicos Islands"]},
"TV":{"name":"Tuvalu","continent":continents["Tuvalu"],"capital":capitals["Tuvalu"]},
"UG":{"name":"Uganda","continent":continents["Uganda"],"capital":capitals["Uganda"]},
"UA":{"name":"Ukraine","continent":continents["Ukraine"],"capital":capitals["Ukraine"]},
"AE":{"name":"United Arab Emirates","continent":continents["United Arab Emirates"],"capital":capitals["United Arab Emirates"]},
"GB":{"name":"United Kingdom","continent":continents["United Kingdom"],"capital":capitals["United Kingdom"]},
"US":{"name":"United States","continent":continents["United States"],"capital":capitals["United States"]},
"UM":{"name":"United States Minor Outlying Islands","continent":continents["United States Minor Outlying Islands"],"capital":capitals["United States Minor Outlying Islands"]},
"UY":{"name":"Uruguay","continent":continents["Uruguay"],"capital":capitals["Uruguay"]},
"UZ":{"name":"Uzbekistan","continent":continents["Uzbekistan"],"capital":capitals["Uzbekistan"]},
"VU":{"name":"Vanuatu","continent":continents["Vanuatu"],"capital":capitals["Vanuatu"]},
"VE":{"name":"Venezuela","continent":continents["Venezuela"],"capital":capitals["Venezuela"]},
"VN":{"name":"Vietnam","continent":continents["Vietnam"],"capital":capitals["Vietnam"]},
"VG":{"name":"Virgin Islands, British","continent":continents["Virgin Islands, British"],"capital":capitals["Virgin Islands, British"]},
"VI":{"name":"Virgin Islands, U.S.","continent":continents["Virgin Islands, U.S."],"capital":capitals["Virgin Islands, U.S."]},
"WF":{"name":"Wallis and Futuna","continent":continents["Wallis and Futuna"],"capital":capitals["Wallis and Futuna"]},
"EH":{"name":"Western Sahara","continent":continents["Western Sahara"],"capital":capitals["Western Sahara"]},
"YE":{"name":"Yemen","continent":continents["Yemen"],"capital":capitals["Yemen"]},
"YU":{"name":"Yugoslavia","continent":continents["Yugoslavia"],"capital":capitals["Yugoslavia"]},
"ZM":{"name":"Zambia","continent":continents["Zambia"],"capital":capitals["Zambia"]},
"ZW":{"name":"Zimbabwe","continent":continents["Zimbabwe"],"capital":capitals["Zimbabwe"]},
}
